import { 
  PaymentStatus, 
  PaymentMethod
} from '@prisma/client';

// ============================================
// Admin Payment Enums (will be generated by Prisma after migration)
// ============================================

export enum RefundStatus {
  REQUESTED = 'REQUESTED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PROCESSING = 'PROCESSING',
  PROCESSED = 'PROCESSED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}

export enum RefundType {
  FULL = 'FULL',
  PARTIAL = 'PARTIAL'
}

export enum RefundMethod {
  ORIGINAL_METHOD = 'ORIGINAL_METHOD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CREDIT_NOTE = 'CREDIT_NOTE',
  WALLET_CREDIT = 'WALLET_CREDIT'
}

export enum ReversalStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}

export enum ReversalType {
  CANCELLATION = 'CANCELLATION',
  INCOMPLETE_PAYMENT = 'INCOMPLETE_PAYMENT',
  DUPLICATE_PAYMENT = 'DUPLICATE_PAYMENT',
  FRAUD_SUSPECTED = 'FRAUD_SUSPECTED',
  TECHNICAL_ERROR = 'TECHNICAL_ERROR',
  TIMEOUT = 'TIMEOUT',
  SYSTEM_ERROR = 'SYSTEM_ERROR'
}

export enum TopUpStatus {
  PENDING = 'PENDING',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}

export enum TopUpMethod {
  BANK_TRANSFER = 'BANK_TRANSFER',
  CASH = 'CASH',
  CARD = 'CARD',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
  PROMOTION = 'PROMOTION'
}

export enum MemberType {
  PATIENT = 'PATIENT',
  CORPORATE = 'CORPORATE',
  AGENT = 'AGENT',
  HOSPITAL = 'HOSPITAL'
}

export enum ReconciliationStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  COMPLETED_WITH_DISCREPANCIES = 'COMPLETED_WITH_DISCREPANCIES',
  FAILED = 'FAILED'
}

export enum AdminPaymentAction {
  VIEW_TRANSACTION = 'VIEW_TRANSACTION',
  SEARCH_TRANSACTIONS = 'SEARCH_TRANSACTIONS',
  EXPORT_TRANSACTIONS = 'EXPORT_TRANSACTIONS',
  INITIATE_REFUND = 'INITIATE_REFUND',
  APPROVE_REFUND = 'APPROVE_REFUND',
  REJECT_REFUND = 'REJECT_REFUND',
  PROCESS_REFUND = 'PROCESS_REFUND',
  COMPLETE_REFUND = 'COMPLETE_REFUND',
  INITIATE_REVERSAL = 'INITIATE_REVERSAL',
  PROCESS_REVERSAL = 'PROCESS_REVERSAL',
  COMPLETE_REVERSAL = 'COMPLETE_REVERSAL',
  TOP_UP_MEMBER = 'TOP_UP_MEMBER',
  APPROVE_TOP_UP = 'APPROVE_TOP_UP',
  UPDATE_PAYMENT_OPTIONS = 'UPDATE_PAYMENT_OPTIONS',
  RUN_RECONCILIATION = 'RUN_RECONCILIATION',
  GENERATE_REPORT = 'GENERATE_REPORT',
  VIEW_RECONCILIATION = 'VIEW_RECONCILIATION'
}

// ============================================
// Query Types
// ============================================

export interface TransactionSearchQuery {
  page?: number;
  limit?: number;
  search?: string;
  transactionId?: string;
  paymentId?: string;
  appointmentId?: string;
  patientName?: string;
  patientEmail?: string;
  patientPhone?: string;
  memberId?: string;
  memberType?: MemberType;
  status?: PaymentStatus | PaymentStatus[];
  paymentMethod?: PaymentMethod | PaymentMethod[];
  minAmount?: number;
  maxAmount?: number;
  startDate?: Date;
  endDate?: Date;
  hospitalId?: string;
  doctorId?: string;
  sortBy?: 'createdAt' | 'amount' | 'status';
  sortOrder?: 'asc' | 'desc';
}

export interface RefundRequestQuery {
  page?: number;
  limit?: number;
  status?: RefundStatus | RefundStatus[];
  refundType?: RefundType;
  memberId?: string;
  memberType?: MemberType;
  requestedById?: string;
  startDate?: Date;
  endDate?: Date;
  minAmount?: number;
  maxAmount?: number;
  sortBy?: 'createdAt' | 'amount' | 'status';
  sortOrder?: 'asc' | 'desc';
}

export interface ReversalRequestQuery {
  page?: number;
  limit?: number;
  status?: ReversalStatus | ReversalStatus[];
  reversalType?: ReversalType;
  memberId?: string;
  autoDetected?: boolean;
  requestedById?: string;
  startDate?: Date;
  endDate?: Date;
  sortBy?: 'createdAt' | 'status';
  sortOrder?: 'asc' | 'desc';
}

export interface TopUpQuery {
  page?: number;
  limit?: number;
  status?: TopUpStatus | TopUpStatus[];
  memberId?: string;
  memberType?: MemberType;
  topUpMethod?: TopUpMethod;
  processedById?: string;
  startDate?: Date;
  endDate?: Date;
  minAmount?: number;
  maxAmount?: number;
  sortBy?: 'createdAt' | 'amount' | 'status';
  sortOrder?: 'asc' | 'desc';
}

export interface ReconciliationQuery {
  page?: number;
  limit?: number;
  status?: ReconciliationStatus;
  performedById?: string;
  startDate?: Date;
  endDate?: Date;
  sortBy?: 'reconciliationDate' | 'createdAt';
  sortOrder?: 'asc' | 'desc';
}

export interface PaymentAuditLogQuery {
  page?: number;
  limit?: number;
  actionType?: AdminPaymentAction | AdminPaymentAction[];
  performedById?: string;
  paymentId?: string;
  refundRequestId?: string;
  reversalRequestId?: string;
  startDate?: Date;
  endDate?: Date;
  sortBy?: 'createdAt';
  sortOrder?: 'asc' | 'desc';
}

// ============================================
// Request DTOs
// ============================================

export interface CreateRefundRequestDTO {
  paymentId: string;
  refundAmount: number;
  refundType: RefundType;
  refundMethod?: RefundMethod;
  reason: string;
  internalNotes?: string;
  idempotencyKey: string;
  metadata?: Record<string, any>;
}

export interface ApproveRefundDTO {
  refundRequestId: string;
  internalNotes?: string;
  idempotencyKey: string;
}

export interface RejectRefundDTO {
  refundRequestId: string;
  rejectionReason: string;
  idempotencyKey: string;
}

export interface ProcessRefundDTO {
  refundRequestId: string;
  gatewayRefundId?: string;
  gatewayResponse?: Record<string, any>;
  idempotencyKey: string;
}

export interface CreateReversalRequestDTO {
  paymentId: string;
  reversalType: ReversalType;
  reason: string;
  internalNotes?: string;
  idempotencyKey: string;
  metadata?: Record<string, any>;
}

export interface ProcessReversalDTO {
  reversalRequestId: string;
  gatewayReversalId?: string;
  gatewayResponse?: Record<string, any>;
  idempotencyKey: string;
}

export interface CreateTopUpDTO {
  memberId: string;
  memberType: MemberType;
  amount: number;
  topUpMethod: TopUpMethod;
  paymentReference?: string;
  reason?: string;
  internalNotes?: string;
  idempotencyKey: string;
  metadata?: Record<string, any>;
}

export interface ApproveTopUpDTO {
  topUpId: string;
  internalNotes?: string;
  idempotencyKey: string;
}

export interface UpdatePaymentOptionsDTO {
  memberId: string;
  memberType: MemberType;
  paymentMethod: PaymentMethod;
  isEnabled: boolean;
  isDefault?: boolean;
  maxTransactionLimit?: number;
  dailyLimit?: number;
  monthlyLimit?: number;
  restrictions?: Record<string, any>;
}

export interface RunReconciliationDTO {
  startDate: Date;
  endDate: Date;
  includeIncomplete?: boolean;
  autoFix?: boolean;
}

// ============================================
// Response Types
// ============================================

export interface TransactionSummary {
  id: string;
  transactionId: string | null;
  appointmentId: string;
  amount: number;
  currency: string;
  paymentMethod: PaymentMethod;
  status: PaymentStatus;
  paidAt: Date | null;
  createdAt: Date;
  patient: {
    name: string;
    email: string;
    phone: string;
  };
  appointment: {
    appointmentNumber: string;
    consultationFee: number;
  };
  session?: {
    doctor: {
      name: string;
    };
    hospital: {
      name: string;
    };
  };
  refundRequests?: {
    id: string;
    status: RefundStatus;
    refundAmount: number;
  }[];
  reversalRequests?: {
    id: string;
    status: ReversalStatus;
  }[];
}

export interface ReconciliationSummary {
  totalTransactions: number;
  matchedTransactions: number;
  mismatchedTransactions: number;
  incompleteTransactions: number;
  totalAmount: number;
  matchedAmount: number;
  mismatchedAmount: number;
  discrepancies: ReconciliationDiscrepancy[];
}

export interface ReconciliationDiscrepancy {
  paymentId: string;
  transactionId: string | null;
  expectedStatus: PaymentStatus;
  actualStatus: PaymentStatus;
  expectedAmount: number;
  actualAmount: number;
  discrepancyType: 'STATUS_MISMATCH' | 'AMOUNT_MISMATCH' | 'INCOMPLETE' | 'DUPLICATE';
  details: string;
}

export interface PaymentStatistics {
  period: {
    startDate: Date;
    endDate: Date;
  };
  totalTransactions: number;
  totalAmount: number;
  successfulTransactions: number;
  successfulAmount: number;
  failedTransactions: number;
  failedAmount: number;
  pendingTransactions: number;
  pendingAmount: number;
  refundedTransactions: number;
  refundedAmount: number;
  averageTransactionAmount: number;
  successRate: number;
  byPaymentMethod: {
    method: PaymentMethod;
    count: number;
    amount: number;
  }[];
  byStatus: {
    status: PaymentStatus;
    count: number;
    amount: number;
  }[];
  dailyTrend: {
    date: string;
    count: number;
    amount: number;
  }[];
}

export interface MemberPaymentSummary {
  memberId: string;
  memberType: MemberType;
  memberName: string;
  memberEmail: string;
  totalTransactions: number;
  totalAmount: number;
  successfulTransactions: number;
  failedTransactions: number;
  refundedAmount: number;
  currentBalance?: number;
  paymentOptions: {
    paymentMethod: PaymentMethod;
    isEnabled: boolean;
    isDefault: boolean;
    maxTransactionLimit: number | null;
    dailyLimit: number | null;
    monthlyLimit: number | null;
  }[];
  recentTransactions: TransactionSummary[];
}

// ============================================
// Audit Log Types
// ============================================

export interface PaymentAuditLogData {
  actionType: AdminPaymentAction;
  paymentId?: string;
  refundRequestId?: string;
  reversalRequestId?: string;
  topUpId?: string;
  performedById: string;
  performedByEmail: string;
  performedByRole: string;
  previousState?: Record<string, any>;
  newState?: Record<string, any>;
  amount?: number;
  currency?: string;
  reason?: string;
  metadata?: Record<string, any>;
  ipAddress?: string;
  userAgent?: string;
  idempotencyKey?: string;
}

// ============================================
// Report Types
// ============================================

export interface PaymentReportParams {
  reportType: 'DAILY_SUMMARY' | 'WEEKLY_SUMMARY' | 'MONTHLY_SUMMARY' | 'CUSTOM_RANGE' | 
              'REFUND_REPORT' | 'REVERSAL_REPORT' | 'RECONCILIATION_REPORT' | 'MEMBER_REPORT';
  startDate: Date;
  endDate: Date;
  memberId?: string;
  memberType?: MemberType;
  hospitalId?: string;
  format?: 'JSON' | 'CSV' | 'PDF';
}

export interface DailySummaryReport {
  date: string;
  totalTransactions: number;
  totalAmount: number;
  successfulTransactions: number;
  failedTransactions: number;
  refundedAmount: number;
  newRefundRequests: number;
  processedRefunds: number;
  reversals: number;
  topUps: number;
  topUpAmount: number;
}
